### ISSUE TITLE
Herein lieth Assignment 1, ready for grading

### ISSUE THREAD

**Issue by anazhibaj** [SES-5215-F2020/anazhibaj-quant#1]
Hi Carole and Sara!

You'll find here the files ready for grading. Thank you for your feedback and help during the process! Looking forward to hearing your thoughts. 

ana

**Comment by anazhibaj** [comment]
The name of the html file is: 200907_Zhibaj-Citizenship.html

**Comment by saratepfer** [comment]
Thank you, Ana! Nice job on this. Please be sure to add an explicit statement of the number of observations in your dataset.

**Comments on Content**
You filter on ESR == 1:6, so I think it is important to specify when stating your population that you are looking at citizens who are older than 16.
You are currently working with a lot of variables. I suggest combining the race variables into a single categorical variable that describes the person's race.

**Comments on the Code**
Line 8: To avoid cluttering your output with package messages, consider replacing this line with ```{r load libraries, message=FALSE}
