### ISSUE TITLE
Assignment 2 is ready to be graded 

### ISSUE THREAD

**Issue by anazhibaj** [SES-5215-F2020/anazhibaj-quant#2]
Hello again! My second assignment is ready to be graded. Thank you for your comments on the first assignment! Looking forward to your feedback. 
Link to html: https://github.com/SES-5215-F2020/anazhibaj-quant/blob/master/200911_Assignment-2.html
Link to Rmd: https://github.com/SES-5215-F2020/anazhibaj-quant/blob/master/200911_Assignment%202.Rmd

**Comment by saratepfer** [comment]
Great job, Ana! Please see a few comments, below:

- line 13: You can replace {r} with {r, message = FALSE} to prevent R from printing unnecessary messages associated with your libraries.
- line 94: you may want to add an indication of units on your income header (e.g., "Income ($)" or similar).
- I think your income plot might be more revealing if you used a smaller binwidth. (e.g., 10,000 or similar order of magnitude).
- Unfortunately your level of education table is not printing the whole table. Try using knitr::kable(shares_education, 
             caption = "insert caption here")
